import { db } from '../db/indexedDb';

/**
 * Scans IndexedDB on app startup for any leaked sample/test records
 * generated by legacy regression self-tests and removes ONLY those records.
 * Real farm data is completely untouched.
 */
export async function cleanupLeakedRegressionTestData(): Promise<{ cleanedCount: number; details: string[] }> {
  const details: string[] = [];
  let cleanedCount = 0;

  try {
    // 1. Animals
    const testAnimalIds = new Set<string>();
    const animals = await db.animals.toArray();
    for (const a of animals) {
      const isTest =
        a.id === 'COW_TEST' ||
        a.id.toLowerCase().includes('test') ||
        a.tag?.toUpperCase().includes('COW-TEST') ||
        a.tag?.toUpperCase().includes('TEST') ||
        a.notes?.includes('টেস্ট') ||
        a.notes?.includes('পরীক্ষামূলক');

      if (isTest) {
        testAnimalIds.add(a.id);
        await db.animals.delete(a.id);
        cleanedCount++;
        details.push(`Animal: ${a.tag || a.id}`);
      }
    }

    // 2. Animal Events
    const events = await db.animalEvents.toArray();
    for (const ev of events) {
      const isTest =
        testAnimalIds.has(ev.animalId) ||
        ev.id.toLowerCase().includes('test') ||
        ev.animalId.toLowerCase().includes('test') ||
        ev.details?.includes('TEST') ||
        ev.details?.includes('টেস্ট') ||
        ev.details?.includes('পরীক্ষামূলক');

      if (isTest) {
        await db.animalEvents.delete(ev.id);
        cleanedCount++;
        details.push(`AnimalEvent: ${ev.id}`);
      }
    }

    // 3. Inventory Items
    const testItemIds = new Set<string>();
    const items = await db.inventoryItems.toArray();
    for (const it of items) {
      const isTest =
        it.id === 'it_feed_test' ||
        it.id.toLowerCase().includes('test') ||
        it.code?.toUpperCase().includes('FEED-TEST') ||
        it.code?.toUpperCase().includes('TEST') ||
        it.nameBn?.includes('টেস্ট') ||
        it.nameBn?.includes('পরীক্ষামূলক') ||
        it.nameEn?.toLowerCase().includes('test');

      if (isTest) {
        testItemIds.add(it.id);
        await db.inventoryItems.delete(it.id);
        cleanedCount++;
        details.push(`InventoryItem: ${it.code || it.nameBn || it.nameEn}`);
      }
    }

    // 4. Stock Movements
    const movements = await db.stockMovements.toArray();
    for (const sm of movements) {
      const isTest =
        testItemIds.has(sm.itemId) ||
        sm.id.toLowerCase().includes('test') ||
        sm.notes?.includes('টেস্ট') ||
        sm.notes?.includes('পরীক্ষামূলক') ||
        sm.notes?.includes('[TEST]');

      if (isTest) {
        await db.stockMovements.delete(sm.id);
        cleanedCount++;
        details.push(`StockMovement: ${sm.id}`);
      }
    }

    // 5. Parties
    const testPartyIds = new Set<string>();
    const parties = await db.parties.toArray();
    for (const p of parties) {
      const isTest =
        p.id === 'pty_supp_test' ||
        p.id === 'pty_cust_test' ||
        p.id.toLowerCase().includes('test') ||
        p.name?.includes('পরীক্ষামূলক') ||
        p.name?.includes('টেস্ট') ||
        p.name?.includes('Test Supplier') ||
        p.name?.includes('Test Customer');

      if (isTest) {
        testPartyIds.add(p.id);
        await db.parties.delete(p.id);
        cleanedCount++;
        details.push(`Party: ${p.name}`);
      }
    }

    // 6. Cash and Bank Accounts
    const accounts = await db.cashBankAccounts.toArray();
    for (const cb of accounts) {
      const isTest =
        cb.id === 'cb_cash_test' ||
        cb.id === 'cb_bank_test' ||
        cb.id === 'cb_inv_test' ||
        cb.id.toLowerCase().includes('test') ||
        cb.name?.includes('(টেস্ট)') ||
        cb.name?.includes('পরীক্ষামূলক') ||
        cb.name?.toLowerCase().includes('test');

      if (isTest) {
        await db.cashBankAccounts.delete(cb.id);
        cleanedCount++;
        details.push(`CashBankAccount: ${cb.name}`);
      }
    }

    // 7. Fixed Assets
    const assets = await db.fixedAssets.toArray();
    for (const fa of assets) {
      const isTest =
        fa.id === 'fa_tractor_test' ||
        fa.id.toLowerCase().includes('test') ||
        fa.name?.includes('পরীক্ষামূলক') ||
        fa.name?.includes('টেস্ট') ||
        fa.name?.toLowerCase().includes('test');

      if (isTest) {
        await db.fixedAssets.delete(fa.id);
        cleanedCount++;
        details.push(`FixedAsset: ${fa.name}`);
      }
    }

    // 8. Loans & Investors
    const loans = await db.loans.toArray();
    for (const ln of loans) {
      const isTest =
        ln.id.toLowerCase().includes('test') ||
        ln.lenderName?.includes('পরীক্ষামূলক') ||
        ln.lenderName?.includes('টেস্ট');

      if (isTest) {
        await db.loans.delete(ln.id);
        cleanedCount++;
        details.push(`Loan: ${ln.lenderName}`);
      }
    }

    const investors = await db.investors.toArray();
    for (const inv of investors) {
      const isTest =
        inv.id.toLowerCase().includes('test') ||
        inv.name?.includes('পরীক্ষামূলক') ||
        inv.name?.includes('টেস্ট');

      if (isTest) {
        await db.investors.delete(inv.id);
        cleanedCount++;
        details.push(`Investor: ${inv.name}`);
      }
    }

    // 9. Purchases & Sales
    const purchases = await db.purchases.toArray();
    for (const pur of purchases) {
      const isTest =
        pur.id.toLowerCase().includes('test') ||
        pur.invoiceNumber?.toUpperCase().includes('TEST') ||
        testPartyIds.has(pur.supplierId);

      if (isTest) {
        await db.purchases.delete(pur.id);
        cleanedCount++;
        details.push(`Purchase: ${pur.invoiceNumber || pur.id}`);
      }
    }

    const sales = await db.sales.toArray();
    for (const sal of sales) {
      const isTest =
        sal.id.toLowerCase().includes('test') ||
        sal.invoiceNumber?.toUpperCase().includes('TEST') ||
        testPartyIds.has(sal.customerId);

      if (isTest) {
        await db.sales.delete(sal.id);
        cleanedCount++;
        details.push(`Sale: ${sal.invoiceNumber || sal.id}`);
      }
    }

    // 10. Journal Entries
    const journals = await db.journalEntries.toArray();
    for (const j of journals) {
      const isTest =
        j.id.toLowerCase().includes('test') ||
        j.voucherNumber?.toUpperCase().includes('TEST') ||
        j.reference?.toUpperCase().includes('TEST') ||
        j.reference?.startsWith('TXN_TEST') ||
        j.narration?.includes('পরীক্ষামূলক') ||
        j.narration?.includes('টেস্ট') ||
        j.narration?.includes('[TEST]') ||
        j.narration?.toLowerCase().includes('regression');

      if (isTest) {
        await db.journalEntries.delete(j.id);
        cleanedCount++;
        details.push(`JournalEntry: ${j.voucherNumber || j.id}`);
      }
    }

    // 11. Reminders & Recurring Expense Templates
    const reminders = await db.reminders.toArray();
    for (const r of reminders) {
      const isTest =
        r.id.toLowerCase().includes('test') ||
        (r.animalId && testAnimalIds.has(r.animalId)) ||
        r.title?.includes('টেস্ট') ||
        r.title?.includes('পরীক্ষামূলক');

      if (isTest) {
        await db.reminders.delete(r.id);
        cleanedCount++;
        details.push(`Reminder: ${r.title || r.id}`);
      }
    }

    const templates = await db.recurringExpenseTemplates.toArray();
    for (const t of templates) {
      const isTest =
        t.id.toLowerCase().includes('test') ||
        t.description?.includes('টেস্ট') ||
        t.description?.includes('পরীক্ষামূলক');

      if (isTest) {
        await db.recurringExpenseTemplates.delete(t.id);
        cleanedCount++;
        details.push(`RecurringTemplate: ${t.description || t.id}`);
      }
    }

    if (cleanedCount > 0) {
      console.log(`[The Goated Farm] Cleaned ${cleanedCount} leaked test records from IndexedDB:`, details);
      window.dispatchEvent(new Event('goted_data_changed'));
    }
  } catch (err) {
    console.warn('[The Goated Farm] Error during test data cleanup:', err);
  }

  return { cleanedCount, details };
}
